In [2]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold

In [3]:
iris = datasets.load_iris()
xtrain, xtest, ytrain, ytest = train_test_split(iris.data, iris.target, test_size=0.2)

In [4]:
clf = LinearRegression()
cross_val_score(clf, xtrain, ytrain)

array([0.95323794, 0.9091774 , 0.88788675, 0.91458109, 0.94104757])

In [5]:
clf = LinearRegression()
cross_val_score(clf, iris.data, iris.target)

array([0.        , 0.85124923, 0.        , 0.76155439, 0.        ])

In [9]:
clf = LinearRegression()
cross_val_score(clf, iris.data, iris.target, cv = KFold(3,True,0))

C:\Users\MOHIT\anaconda3\lib\site-packages\sklearn\utils\validation.py:68: FutureWarning: Pass shuffle=True, random_state=0 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


array([0.90322728, 0.92527008, 0.94214064])